eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.137:8761/eureka/
      
server:
  port: 8768
  
spring:
  application:
    name: eshop-one-service

feign:
  hystrix:
    enabled: true